USE PreguntadOrt;

INSERT INTO Preguntas(IdCategoria, IdDificultad, Enunciado, Foto)
VALUES
    (1, 1, '¿Cual es el pais mas grande del mundo por superficie?', 'https://p1.pxfuel.com/preview/42/307/649/travel-pinned-pinning-maps.jpg'),
    (1, 1, '¿Cual es la capital de Portugal?', NULL),
    (1, 2, '¿En que continente se encuentra el Sahara?', NULL),
    (1, 2, '¿Cual es el pais mas grande de Africa?', NULL),
    (1, 3, '¿En que ano se formo el continente de Gondwana?', NULL),
    (1, 3, '¿Que pais tiene la mayor cantidad de lenguas oficiales?', NULL),
    (2, 1, '¿Que gas es esencial para la respiracion humana?', NULL),
    (2, 1, '¿Como se llama el proceso por el cual las plantas producen su alimento?', NULL),
    (2, 1, '¿Como se llama el cientifico que formulo la teoria de la relatividad?', NULL),
    (2, 2, '¿Que tipo de energia se almacena en los alimentos?', NULL),
    (2, 2, '¿Cual es la funcion principal de los globulos rojos?', NULL),
    (2, 3, '¿Que elemento tiene el numero atomico 79?', NULL),
    (2, 3, '¿Que es la materia oscura?', NULL),
    (3, 1, '¿En que ano comenzo la Segunda Guerra Mundial?', NULL),
    (3, 1, '¿Que imperio era conocido por su sistema de acueductos y caminos en Europa?', NULL),
    (3, 2, '¿Quien fue el ultimo zar de Rusia?', NULL),
    (3, 2, '¿Que dinastia goberno China durante la mayor parte de la Edad Media?', NULL),
    (3, 3, '¿Cual fue la causa principal de la caida del Imperio Bizantino?', NULL),
    (3, 3, '¿Cual fue el proposito principal del Proyecto Manhattan durante la Segunda Guerra Mundial?', NULL),
    (4, 1, '¿Quien gano el Tour de Francia en 2023?', NULL),
    (4, 1, '¿Que deporte se juega con un balon y una canasta en cada extremo del campo?', NULL),
    (4, 2, '¿Cual es el nombre del campeonato de Formula 1?', NULL),
    (4, 2, '¿En que deporte se compite en los 100 metros lisos?', NULL),
    (4, 3, '¿Cual es la distancia exacta de una maraton en kilometros?', NULL),
    (4, 3, '¿En que ano se introdujo el uso del videoarbitraje (VAR) en el futbol profesional?', NULL),
    (5, 1, '¿Quien escribio "Don Quijote de la Mancha"?', NULL),
    (5, 1, '¿Cual es el nombre del famoso ballet ruso que cuenta la historia de un cisne?', NULL),
    (5, 2, '¿Que escritor britanico es conocido por su serie de libros sobre Harry Potter?', NULL),
    (5, 2, '¿Cual es el nombre del famoso escultor que creo "El David" en la Florencia renacentista?', NULL),
    (5, 3, '¿Que movimiento artistico se caracteriza por la experimentacion y la ruptura con las formas tradicionales?', NULL),
    (5, 3, '¿Cual es el nombre de la corriente literaria que busca representar la realidad de manera objetiva?', NULL),
    (6, 1, '¿Que programa de television se basa en un grupo de amigos que viven en Nueva York?', NULL),
    (6, 1, '¿Cual es el nombre del famoso personaje de Disney que vive en el reino de Arendelle?', NULL),
    (6, 2, '¿Cual es el nombre del famoso programa de concursos que presenta desafios de resistencia?', NULL),
    (6, 2, '¿Que director es conocido por sus peliculas de terror como "El resplandor"?', NULL),
    (6, 3, '¿Que autor escribio la trilogia "El juego de Ender"?', NULL),
    (6, 3, '¿Que director es conocido por su trilogia de peliculas sobre el "Caballero Oscuro"?', NULL),
    (7, 1, '¿Quien es conocido por sus trucos de magia y ha tenido programas de television exitosos?', NULL),
    (7, 1, '¿Que tipo de mercado se especializa en la venta de articulos de segunda mano?', NULL),
    (7, 2, '¿Que libro de autoayuda se enfoca en la superacion de obstaculos personales y profesionales?', NULL),
    (7, 2, '¿Que programa de television es conocido por su formato de competencias entre chefs profesionales?', NULL),
    (7, 3, '¿Cual es el nombre del show de TV que presenta una competencia de talento internacional?', NULL),
    (7, 3, '¿Qué espectaculo presenta desafios extremos en una competencia?', NULL);